<?xml version="1.0"?>

<!DOCTYPE document [
	 <!ELEMENT document (category+,bibliography)>
	 <!ELEMENT category (chapter+)>
	 <!ELEMENT chapter (section+)>
	 <!ELEMENT section (#PCDATA|link|image|verbatim|dependency|exercise|ref|code|list|enumeration|subsection)*>
         <!ELEMENT subsection (#PCDATA|link|image|verbatim|exercise|ref|code|list|enumeration|subsubsection|dependency)*>
         <!ELEMENT subsubsection (#PCDATA|link|image|verbatim|exercise|ref|code|list|enumeration)*>
         <!ELEMENT list (item+)*>
         <!ELEMENT enumeration (item+)*> 
         <!ELEMENT item (#PCDATA|link|code|ref|enumeration|list)*>
	 <!ELEMENT link (#PCDATA)>
	 <!ELEMENT image (#PCDATA)>
	 <!ELEMENT verbatim (#PCDATA)>
	 <!ELEMENT code (#PCDATA)>
	 <!ELEMENT dependency (#PCDATA)>
	 <!ELEMENT exercise (#PCDATA|ref|enumeration|list|code)*>
	 <!ELEMENT ref (#PCDATA)>
	 <!ELEMENT bibliography (bibitem*)>
	 <!ELEMENT bibitem (#PCDATA)>
	 <!ATTLIST category title CDATA #IMPLIED label ID #REQUIRED>
	 <!ATTLIST chapter title CDATA #REQUIRED label ID #REQUIRED>
	 <!ATTLIST section title CDATA #REQUIRED label ID #REQUIRED>
         <!ATTLIST subsection title CDATA #REQUIRED label ID #REQUIRED>
         <!ATTLIST subsubsection title CDATA #REQUIRED label ID #REQUIRED> 
	 <!ATTLIST link url CDATA #REQUIRED>
	 <!ATTLIST image src CDATA #REQUIRED alt CDATA #REQUIRED height CDATA #REQUIRED width CDATA #REQUIRED>
	 <!ATTLIST bibitem label ID #REQUIRED>
	 <!ENTITY ne "&lt;&gt;">
]>

<document>
	<category title="About the tutorial" label="about-tutorial">
		<chapter title="Introduction" label="about-intro">
			<section title="How to use this tutorial" label="intro-tutorial">
				This tutorial is divided into four parts, which contain chapters, which further contain links to the tutorial's sections.
				In the menu at the right, the parts and chapters are collapsible.
				\\\\
				This part is  "About this tutorial," with information about using, and amending the tutorial.
				"Sage as a Calculator" shows how to do arithmetic, evaluate functions, plot graphs, 
				compute derivatives and integrals  (eventually) and do other things that involve fairly simple commands.
				
				This material is similar to computations one would do with a calculator, 
				and the chapter is intended to be understandable by a motivated pre-calculus or calculus student.
				The chapter "Programming in Sage" teaches some of the more subtle issues about how sage computes: 
				the different ways that Sage handles numbers, how to use
				variables, lists, strings, and sets.  The chapter also shows how to save and restore your work, and how to program 
				with iterative loops, conditional statements, and user created functions.
				The chapter "Mathematical Structures" introduces the topics that one finds in college level curriculum: number theory, groups, rings, fields, etc.
				\\\\
				Throughout this tutorial we will explore how to use Sage to  perform calculations.
				In each section we have tried to include exercises for practice and problems for more extensive exploration.
				\\\\
				At the beginning of each section is a list of things which you should understand before proceeding.
				This list follows the text "You should be familiar with."
				Clicking one of these links will populate and expand the window for "Hal" (our favorite computer of the new millenium) at the bottom of the screen.
				It will contain a concise treatment of Sage concepts which are important to the section you are reading.
				Click "Hal" in its titlebar to collapse or expand this window
				\\\\
				Some sections may contain numbered citations such as "[1]."
				At the bottom of a page with at least one citation will be a bibliography section,
				with the entries correspondingly numbered.
			</section>
			<section title="About Sage" label="intro-sage">
				Sage is a free open source mathematical software system <ref>sageweb</ref>.
				Originally created for research into mathematics, it has been evolving into a powerful tool for math education.
				Sage combines numerous  other mathematical software packages using a single interface.
				\\\\
				As an open source project, Sage invites contributions from all of its users.
				This tutorial is one of many sources of information for learning about Sage.  See the Sage webpage for more information.
			</section>
			<section title="Installing Sage" label="intro-install-sage">
				To be done:
			</section>
			<section title="Helpful Tips" label="tips">
				To be done:
				\\\\
				Tab completion...
				\\
				Getting help using '?' at the prompt...
				\\
				The notebook
			</section>
		</chapter>
		<chapter title="Building this Tutorial" label="about-build">
			<section title="Credits and License" label="build-license">
				The content and code for this tutorial were written by Ryan Rosenbaum and David Monarres under the supervision of Mike  O'Sullivan.
				The work was supported by San Diego State University's Presidential Leadership Fund.
				\\\\
				This work is licensed under the <link url="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons
				Attribution-ShareAlike 3.0 License</link>.   You are free to share and to remix, but attribution should be given to 
				the original funder and creators.
			</section>
			<section title="Editing the content" label="build-edit">
				Additions to this tutorial are very welcome.  
				Please let us know of any new material so that we may incorporate it into our version.\\\\
				The only file that needs to be edited to add or remove content is content.xml.  
				There is a template at the beginning of the file for adding a chapter and a section within the chapter. 
				\\\\
				We have four parts to the tutorial:  "How to use this tutorial" has  basic instructions about using and amending the tutorial, 
				and the others have mathematical content. "Sage as a Calculator" is intended, as the title suggests, 
				to cover straightforward computations, and we have designed it to be fairly accessible to an entering college student, 
				or to a bright high school student.
				\\\\
				"Programming in Sage" eases the transition to higher level mathematics by treating topics that relate to the interface 
				between mathematical concepts and computational issues.  This chapter covers 
				basic structures like: Lists, sets and strings; 
				The universe for a number or variable, rational numbers versus real numbers (of specificied precision); Programming essentials like conditionals 
				and iterative computation; File handling, data handling etc.
				\\\\
				In "Mathematical Structures" the emphasis is on learning about specific mathematical structures, which have a Sage class
				associated to them.  
			</section>
			<section title="Tools Used" label="build-used">
				This tutorial makes extensive use of the freely available open source software including, but not limited to, the following:
				\\\\
				<list>
					<item> 
						<link url="http://jquery.com/">jQuery</link>,  is a fast and concise JavaScript library which  
						simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development.
						\\\\
					</item>
					<item>
						<link url="http://www.w3.org/math/">MathML</link>, is a collection of XML tags which can be used to 
						mark up an equation in terms of its presentation and also its semantics. MathML attempts to capture something of the 
						meaning behind equations rather than concentrating entirely on how they are going to be formatted out on the screen.
						\\\\
					</item>
					<item>
						<link url="http://www.maths.nottingham.ac.uk/personal/drw/lm.html">LaTexMathML.js</link>: 
						A JavaScript program that does the conversion from basic
						LaTeX to MathML for display in the browser. Written by Dr Douglas R. Woodall of the University of Nottingham 
						which was based on Peter Jipsen's 
						<link url="http://www1.chapman.edu/~jipsen/mathml/asciimath.html"> ASCII2MathML </link> script. 
						\\\\
					</item>
				</list>
				\\\\
			</section>
		</chapter>
	</category> 

	<category title="Sage as a calclator" label="sage-as-calc">
		<chapter title="Arithmetic and functions" label="arithmetic-functions">
			<section title="Basic Arithmetic" label="basic-arithmetic">
				The basic operators are $ + , - , * , $ and $ / $ for addition, subtraction, multiplication and division, respectively.
				Additionally, we use $ ^ $ for exponents.
				<verbatim>
	sage: 1+1
	2
	sage: 103-101
	2
	sage: 7*9
	63
	sage: 7337/11
	667
	sage: 11/4
	11/4
	sage: 2^5
	32
				</verbatim>
				Also, we place the $ - $ symbol in front of a number to indicate it is negative
				<verbatim>
	sage: -6
	-6
	sage: -11+9
	-2
				</verbatim>
				As we would expect, Sage aheres to the standard order of operations, PEMDAS 
				(parenthesis, exponents, multiplication, division, addition, subtraction).
				<verbatim>
	sage: 2*4^2+1  
	33
	sage: (2*4)^2+1
	65
	sage: 2*4^(2+1)
	128
	sage: -3^2
	-9
	sage: (-3)^2
	9
				</verbatim>
				There is a subtle thing to note about Sage.
				When we divided $ 11 $ by $ 4 $, Sage returned $ \frac{11}{4} $ instead of 2.75.
				If we wish to have Sage return a decimal we must input a decimal.
				Here are a few examples demonstrating this
				<verbatim>
	sage: 11/4.0 
	2.75000000000000
	sage: 11/4.
	2.75000000000000
	sage: 11.0/4
	2.75000000000000
	sage: 11/4*1.
	2.75000000000000
				</verbatim>
			</section>
			<section title="Division and factoring" label="basic-division">
				<dependency>basic-arithmetic</dependency>
				When we divide an integer $ a $ by another integer $ b $ we call obtain a quotient $ q $ and a remainder $ r $.
				For example, if $ a=14 $ and $ b=4 $, then $ a = 3b+2 $.
				Hence our quotient is $ q=3 $ and our remainder is $ r=2 $.
				To calculate the quotient we use the $ // $ operator and to calculate the remainder we use the $ % $ operator.
				<verbatim>
	sage: 14 // 4
	3
	sage: 14 % 4
	2
				</verbatim>
				Note that the quotient operator $ // $ is two backslashes.
				If we wish to obtain the pair $ (q,r) $ all at once, we may use the <code>divmod</code> function
				<verbatim>
	sage: divmod(14,4)
	(3, 2)
				</verbatim>
				We say that $ b $ divides $ a $ if we get a remainder of $ 0 $ when we divide $ a $ by $ b $.
				Integers in Sage have a built-in function ( or 'method' ) which allows us to check if an integer divides another:
				<verbatim>
	sage: 3.divides(15)
	True
	sage: 5.divides(17)
	False
				</verbatim>
				Along these lines, given an integer $ a $, we call the collection of integers which divide $ a $ its divisors.
				Integers in Sage have the <code>divisors</code> method built-in as well:
				<verbatim>
	sage: 12.divisors()
	[1, 2, 3, 4, 6, 12]
	sage: 101.divisors()
	[1,101]
				</verbatim>
				When the divisors of an integer are 1 and itself we say it is a prime number.
				To check if a number is prime in sage, we use the 'is_prime' method.
				<verbatim>
	sage: (2^19-1).is_prime()
	True
	sage: 153.is_prime()
	False
				</verbatim>
				We should take note of the parentheses around the number in the first example,
				which are important to the order of operations in Sage.
				Try evaluating '2^19-1.is_prime()' and see what happens.
				\\\\
				Related to the divisors of an integer are its prime factors.
				We use the <code>factor</code> method to obtain the prime factorization of an integer.
				<verbatim>
	sage: 62.factor()
	2 * 31
	sage: 63.factor()
	3^2 * 7
				</verbatim>
				If we are interested in simply knowing which prime numbers divide an integer, we may use the <code>prime_divisors</code> 
				(or <code>prime_factors</code>) method.
				<verbatim>
	sage: 24.prime_divisors() 
	[2, 3]
	sage: 63.prime_factors()
	[3, 7]
				</verbatim>
				The final fundamental idea in factoring is that of the greatest common divisor.
				A common divisor of two integers $ a $ and $ b $ is any integer which is a divisor of each.
				The greatest common divisor (gcd), not too surprisingly, is then the greatest integer which divides each integer.
				We use the <code>gcd</code> function to calculate the greatest common divisor
				<verbatim>
	sage: gcd(14,63)                                                                           
	7
	sage: gcd(15,19)  
	1
				</verbatim>
				Notice that if two integers share no common prime factor, then their gcd will be $ 1 $.
				\\\\
				Related to the gcd is the least common multiple (lcm) of two integers.
				The least common multiple of $ a $ and $ b $ is the smallest integer which is divisible by $ a $ and $ b $.
				We use <code>lcm</code> in Sage to calculate the least common multiple
				<verbatim>
	sage: lcm(4,5)
	20
	sage: lcm(14,21)
	42
				</verbatim>
				<exercise>
					Calculate $gcd(a,b)$, lcm($a$,$b$) and $ab$ for the pairs $ (a,b) =  (2,5) $, $ (4,10) $ and $ (18,51) $.
					How do the gcd, lcm and the product of the numbers relate?
				</exercise>
			</section>
			<section title="Basic functions and constants" label="basic-functions">
				<dependency>basic-arithmetic</dependency>
				Nearly all standard functions we run into in mathematics are included in Sage.
				In this section, we shall cover some of the more fundamental functions and constants, including:
				max, min, abs, floor, ceil, trig functions, exponentials, logarithms, $ e $, $ \pi $ and the golden ratio $ \phi $.
				\\\\
				The functions <code>max</code> and <code>min</code> return the maximum and minimum of a set of numbers.
				<verbatim>
	sage: max(1,5,8)
	8
	sage: min(1/2,1/3)
	1/3
				</verbatim>
				We may input any number of arguments into the <code>max</code> and <code>min</code> functions.
				\\\\
				The absolute value of a number $ x $ is denoted $ |x| $.
				For example, $ |-4| = |4| = 4 $.
				In Sage we use the function <code>abs</code> to obtain the absolute value
				<verbatim>
	sage: abs(-10)
	10
	sage: abs(4)
	4
				</verbatim>
				Another set of important functions are those that round numbers to integers.
				The <code>floor</code> function rounds down to the nearest integer, while <code>ceil</code> rounds up.
				Typically we denote floor with $ \lfloor x \rfloor $ and ceiling by $ \lceil x \rceil $.
				<verbatim>
	sage: floor(2.1)
	2
	sage: ceil(2.1)
	3
				</verbatim>
				We need to be very careful with decimals while using <code>floor</code> and <code>ceil</code>.
				For, consider the following example
				<verbatim>
	sage: floor(1/(2.1-2))
	9
				</verbatim>
				This is clearly not correct: $ \lfloor 1/(2.1-2) \rfloor = \lfloor 1/.1 \rfloor = \lfloor 10  \rfloor = 10$.
				So what happened?
				<verbatim>
	sage: 1/(2.1-2)
	9.99999999999999
				</verbatim>
				Computers use binary notation, while we are accustomed to decimal notation.
				The number $ 2.1 $ in decimal notation is quite simple and short,
				but when converted to binary it is $ 10.0\overline{0011} = 10.0001100110011\ldots $
				Since computers cannot store an infinite number of digits, this gets rounded off somewhere.
				Resulting in the slight error we saw.
				In Sage, however, rational numbers (fractions) have perfect precision, so we will never see this error.
				<verbatim>
	sage: floor(1/(21/10-2))
	10
				</verbatim>
				Due to this, it is a good idea to use rational numbers whenever possible instead of decimals.
				\\\\
				We use <code>sqrt()</code> to calculate the square root.  As with fractions, if we want a decimal expression we need to give a decimal input.   
				<verbatim>
	sage: sqrt(3)
	sqrt(3)
	sage: sqrt(3.0)
	1.73205080756888
	sage: sqrt(8,3)

				</verbatim>
				\\\\
				To compute other roots, use a rational exponent.  Sage can compute any rational power. 
				If either the exponent or the base is a decimal then the output will be a decimal.
				<verbatim>
	sage: 3^(1/2)
	sqrt(3)
	sage: (3.0)^(1/2)
	1.73205080756888
	sage: 8^(1/2)
	2*sqrt(2)
	sage: 8^(1/3)
	2
				</verbatim>
				The trigonometric functions are exactly what one finds in textbooks: for sine and cosine we use the familiar  <code>sin</code> and <code>cos</code>.
				<verbatim>
	sage: sin(1)
	sin(1)
	sage: sin(1.0)
	0.841470984807897
	sage: cos(3/2)
	cos(3/2)
	sage: cos(3/2.0)
	0.0707372016677029
				</verbatim>
				Again we see the same behavior that we saw with <code>sqrt</code>.
				Essentially, Sage wants to give us an exact answer;
				there is, however, no way to simplify $ \sin(1) $.
				So why bother? Well, some expressions involving sine can indeed be simplified.
				For example, an important identity from geometry is that $ \sin(\frac{\pi}3) = \frac{\sqrt 3} 2 $.
				Sage has a built-in symbolic $\pi$, and understands this identity
				<verbatim>
	sage: pi
	pi
	sage: sin(pi/3)
	1/2*sqrt(3)
				</verbatim>
				When we type <code>pi</code> in Sage we are dealing exactly with $ \pi $, not some numerical approximation.
				However, we can call for a numerical approximation using the <code>n</code> method
				<verbatim>
	sage: pi.n()
	3.14159265358979
	sage: sin(pi)
	0
	sage: sin(pi.n())
	1.22464679914735e-16
				</verbatim>
				We see that when using the symbolic <code>pi</code> Sage understands the identity $ sin(\pi) = 0 $.
				When we use the approximation, however, we get an approximation back.
				The <code>e-15</code> is the shorthand for $10^-15$.
				Basically <code>1.22464679914735e-16</code> should be zero, but there are errors due to the approximations.
				Here are a few commonly known examples of using the symbolic, precise <code>pi</code> vs the numerical approximation
				<verbatim>
	sage: sin(pi/6)                                                                            
	1/2
	sage: sin(pi.n()/6)
	0.500000000000000
	sage: sin(pi/4)
	1/2*sqrt(2)
	sage: sin(pi.n()/4)
	0.707106781186547
				</verbatim>
				There are in fact some special angles for which the value of sine or cosine can be cleverly simplified.
				<verbatim>
	sage: sin(pi/10)                                                                           
	1/4*sqrt(5) - 1/4
	sage: cos(pi/5)
	1/4*sqrt(5) + 1/4
	sage: sin(5*pi/12)
	1/12*(sqrt(3) + 3)*sqrt(6)
				</verbatim>
Other trigonometric functions, the inverse trigonometric functions and hyperbolic functions are also available.
                                <verbatim>
	sage: arctan(1.0)
	0.785398163397448
	sage: sinh(9.0)
	4051.54190208279
				</verbatim>
				Similar to <code>pi</code> Sage has a built-in symbolic constant for the number $ e $, the base of the natural logarithm.
				This constant is named <code>e</code>
				<verbatim>
	sage: e
	e
	sage: e.n()
	2.71828182845905
				</verbatim>
				While some might be familiar with using $ \ln(x) $ for natural log  and $ \log(x) $ to represent log base 10,
				these both represent logarithms base $ e $ written as such.
				However, with the <code>log</code> function we may specify a different base as a second argument.
				That is $ \log_b(x) $ in Sage is written <code>log(x,b)</code>
				<verbatim>
	sage: ln(e)
	1
	sage: log(e)
	1
	sage: log(e^2)
	2
	sage: log(10)
	log(10)
	sage: log(10.0)
	2.30258509299405
	sage: log(100,10)
	2
				</verbatim>
				Exponentiation base $ e $ is done using the <code>exp</code> function
				<verbatim>
	sage: exp(2)
	e^2
	sage: exp(2.0)
	7.38905609893065
	sage: exp(log(pi))
	pi
				</verbatim>
				<exercise>
					<enumeration>
						<item>Compare $e^{i\pi}$ with a numerical approximation of it using <code>pi.n()</code>. </item>
						<item>Verify some of the standard trigonometric identities.  See if you can find instance where using the numerical approximation <code> pi.n()</code> leads to an error.</item>
					</enumeration>
				</exercise>

			</section>
			
			<section title="Variables, Equations and Inequalities" label="basic-equations">
				<dependency>basic-functions</dependency>
				
				
				When working with variables in Sage we must first declare them. We can use both simple letter and full names when declaring a 
				symbolic variable.
				
				<verbatim>
	sage: x,y,z,t = var("x y z t")
	sage: phi, theta, rho = var("phi theta rho") 
				</verbatim>
				
				Attempting to use a symbolic variable before it has been declared will cause Sage to complain  loudly.
				
				<verbatim>
	sage: u
	sage: u
	...
	NameError: name 'u' is not defined
				</verbatim>

				We can un-declare a symbolic variable by using the <code>restore</code> command.
				<verbatim>
	sage: restore('phi')
	sage: phi
	...
	NameError: name 'phi' is not defined
				</verbatim>

				In Sage,  equations and inequalities are defined using the conditional operators <code>==</code>, <code>&lt;=</code>, and <code>&gt;=</code> 
				and will return either <code>True</code>,<code>False</code>, or just the equation/inequality.
				
				<verbatim>
	sage: 9 == 9
	True
	sage: 9 &lt;= 10
	True
	sage: 3*x - 10 == 5
	3*x - 10 == 5
				</verbatim>
				We can solve symbolic equations and inequalities by using the, aptly named, <code>solve</code> command. 
				<verbatim>
	sage: solve(3*x - 2 == 5,x)
	[x == (7/3)]
	sage: solve( 2*theta -5 == 1, theta)
	[theta == 3]
	sage: solve( 2*t - 5 >= 17,t)
	[[t >= 11]]
	sage: solve( 3*x -2 &gt; 5, x) 
	[[x &gt; (7/3)]]
				</verbatim>
				
				\\\\
				We can also solve for equations which have multiple solutions, Sage returns these as a list. 
				
				<verbatim>
	sage: solve( x^2 + x  == 6, x)
	[x == -3, x == 2]
	sage: solve(2*x^2 - x + 1 == 0, x)
	[x == -1/4*I*sqrt(7) + 1/4, x == 1/4*I*sqrt(7) + 1/4]
	sage: solve( exp(x) == -1, x)
	[x == I*pi]
				</verbatim>
				\\\\
				The solution sets of certain inequalities consist of the union and intersection of open intervals
				<verbatim>
	sage: solve( x^2 - 6 &gt;= 3, x )
	[[x &lt;= -3], [x &gt;= 3]]
	sage: solve( x^2 - 6 &lt;= 3, x )
	[[x &gt;= -3, x &lt;= 3]]
				</verbatim>
				
				Small systems of equations can be solved also and can result in either a unique solution, infinitely many solutions, or no solutions at all. 
				
				
				<verbatim>
	sage: solve( [3*x - y == 2, -2*x -y == 1 ], x,y)
	[[x == (1/5), y == (-7/5)]]
	sage: solve( [	2*x + y == -1 , -4*x - 2*y == 2],x,y)
	[[x == -1/2*r1 - 1/2, y == r1]]
	sage: solve( [	2*x - y == -1 , 2*x - y == 2],x,y)   
	[]
				</verbatim>
				  
				In the second equation show above, <code>r1</code> signifies that there is a free variable which parameterizes the solution set. 
				When there is more than one free variable, Sage enumerates them 
				
				<verbatim>
	sage: solve([ 2*x + 3*y + 5*z == 1, 4*x + 6*y + 10*z == 2, 6*x + 9*y + 15*z == 3], x,y,z)
	[[x == -5/2*r1 - 3/2*r2 + 1/2, y == r2, z == r1]]
				</verbatim>

				Using <code>solve</code> can be very slow for large systems of equations. For these systems, it is best to use the 
				<link url="http://sagemath.org/doc/tutorial/tour_linalg.html">linear algebra</link> functions as they are 
				quite efficient.
				\\\\ 
				The <code>solve()</code> command will attempt to express the solution of an equation without the use of floating point numbers. 
				If this cannot be done, it will return the solution in a symbolic form
				\\\\
				<verbatim>
	sage: solve( sin(x) == x, x)
	[x == sin(x)]
	sage: solve( exp(x) - x == 0 , x)
	[x == e^x]
	sage: solve( cos(x) - sin(x) == 0 , x)
	[sin(x) == cos(x)]
	sage: solve( cos(x) - exp(x) == 0 , x)
	[cos(x) == e^x]
				</verbatim>

				To find a numeric approximation of the solution we can use the <code>find_root()</code> command. 
				Which requires both the expression and a closed interval on which to search for a solution
				
				<verbatim>
	sage: find_root(sin(x) == x, -pi/2 , pi/2)
	0.0
	sage: find_root(sin(x) == cos(x), pi, 3*pi/2) 
	3.9269908169872414

				</verbatim>
				  
				<code>find_root()</code> will only return one solution on the specified interval, if one exists. It will not find the complete 
				solution set over the entire real numbers. 
				\\\\

				To find a complete set of solutions, the reader must use <code>find_root()</code>
				repeatedly over cleverly selected intervals. Sadly, at this point, Sage cannot do all of the thinking for us.
				This feature is not planned until Sage 10. :-)
				\\\\
			</section>
			<section title='Basic Statistics' label='basic-stat'>
				<subsection title="Descriptive Stats" label='basic-stat-desc'>
					In this section we will discuss the use of some of the basic descriptive statistic functions availble for use in Sage.
					\\\\
					To demonstrate their usage we will first generate a psudo-random list of integers to describe.
					The <code> random()</code> function generates a random number from $\left[ 0 , 1 \right)$, so we will use a trick.
					Note, by the nature of random number generation your list of numbers will be different.
					<verbatim>
	sage: data = [  floor(tan( pi* random() - pi/2.1 )) for i in [ 1 .. 20 ] ] 
	sage: data                                                                 
	[1, -1, -7, 0, -4, -1, -2, 1, 3, 5, -1, 
	25, -5, 1, 2, 0, 1, -1, -1, -1]
					</verbatim>
					We can compute the mean, median, mode, variance, and standard deviation of this data. 
					<verbatim>
	sage: mean(data)
	3/4
	sage: median(data)
	-1/2
	sage: mode(data)  
	[-1]
	sage: variance(data)
	3023/76
	sage: std(data)     
	1/2*sqrt(3023/19)
					</verbatim>
					Note that both the <code>std</code> and <code>variance</code> are computed in their unbiased forms. 
					It we want to bias these measures then you can use the <code>bias=True</code> option. 
					\\\\
					We can also compute a rolling, or moving, average of the data with <code>moving_average</code>.
					<verbatim>
	sage: moving_average(data,4)
	[-7/4, -3, -3, -7/4, -3/2, 1/4, 7/4, 2, 8, 6, 5, 23/4, 
	-1/2, 1, 1/2, -1/4, -1/2]
	sage: moving_average(data,10)
	[-1/2, -7/10, 19/10, 21/10, 11/5, 14/5, 29/10, 16/5, 3, 13/5, 2]
	sage: moving_average(data,20)
	[3/4]
					</verbatim>
				</subsection>
			</section>
		</chapter>
		<chapter title="Plotting" label="sage-calc-plotting">
			<section title="Basic Plotting and Graphics" label="basic-plotting">
				<dependency> basic-functions </dependency>
				\\\\
				Sage has  many ways for us to visualize the mathematics with which we are working.
				In this section we will quickly get the reader up to speed with some of the basic commands used
				when plotting functions and working with graphics.
				
				\\\\
				
				To produce a basic plot of $sin(x)$ from $x=-\frac{\pi}{2}$ to $x = \frac{\pi}{2}$ 
				we will use the <code>plot</code> command.
				<verbatim>
	sage: f(x) = sin(x)
	sage: p = plot(f(x), (x, -pi/2, pi/2))
	sage: p.show()
				</verbatim>
				<image alt="Plot of sin(x) from x=-pi/2 to pi/2" src="pics/sin_plot.png" height="300" width="400" />
				
				\\\\
				By default, the plot created will be quite plain. To add axis labels and make our plotted linepurple, we can alter 
				the <code>plot</code> attribute by adding the <code>axes_labels</code> and <code>color</code> options
				<verbatim>
	sage: p = plot(f(x), (x,-pi/2, pi/2), axes_labels=['x','sin(x)'], color='purple') 
	sage: p.show()
				</verbatim>
				<image alt="plot of sin with purple line and basic axis labels" src="pics/sin_plot_purple_labels.png" height="300" width="400" />
				\\\\
				  
				The <code>color</code> option accepts string color designations ( 'purple', 'green', 'red', 'black', etc...), 
				an RGB triple such as (.25,.10,1),  or an HTML-style hex triple such as  #ff00aa.
				\\\\
				We can change the style of line, whether it is solid, dashed,  and it's thickness by using the <code>linestyle</code> and the
				<code>thickness</code> options.
				<verbatim>
	sage: p = plot(f(x), (x,-pi/2, pi/2), linestyle='--', thickness=3) 
	sage: p.show()
				</verbatim>
				<image alt="Plot of sin(x) using a thick dashed blue line" src="pics/sin_plot_dashed_thick.png" height="300" width="400" />
				\\\\
				We can display the graphs of two functions on the same axes by adding the plots together. 
				<verbatim>
	sage: f(x) = sin(x)
	sage: g(x) = cos(x)
	sage: p = plot(f(x),(x,-pi/2,pi/2), color='black')
	sage: q = plot(g(x), (x,-pi/2, pi/2), color='red')
	sage: r = p + q 
	sage: r.show()
				</verbatim>
				<image alt="Plot of sin(x) and cos(x) on the same axes" src="pics/sin_cos_plot.png" height="300" width="400" />
				\\\\
				To tie together our plotting commands with some material we have learned earlier, let's use the <code>find_root</code> 
				command to find the point where $\sin(x)$ and $\cos(x)$ intersect. We will then add this point to the graph and label it. 
				<verbatim>
	sage: find_root( sin(x) == cos(x),-pi/2, pi/2 )                           
	0.78539816339744839
	sage: P = point( [(0.78539816339744839, sin(0.78539816339744839))] )      
	sage: T = text("(0.79,0.71)", (0.78539816339744839, sin(0.78539816339744839) + .10))
	sage: s = P + r + T                                                
	sage: s.show()
				</verbatim>
				<image alt="sin(x) and cos(x) on same axes with point of intersection labeled" src="pics/sin_cos_point_plot.png" height="300" width="400" />
				\\\\
				Sage handles many of the details of producing "nice" looking plots in a way that is transparent to the user. However there are
				times in which Sage will produce a plot which isn't quite what we were expecting.
				<verbatim>
	sage: f(x) = (x^3 + x^2 + x)/(x^2 - x -2 )
	sage: p = plot(f(x), (x, -5,5))
	sage: p.show()
				</verbatim>
				<image alt="Plot of rational function with asymptotes" src="pics/rat_func_with_asymptotes.png" height="300" width="400" />
				\\\\
				The vertical asymptotes of this rational functions cause Sage to adjust the aspect ratio of the plot
				to display the rather large $y$ values near $x=-1$ an $x=2$. This however obfuscates most of the features of this function
				in a way that we may have not intended. To remedy this we can explicitly adjust the vertical and horizontal limits of our plot
				<verbatim>
	sage: p.show(xmin=-2, xmax=4, ymin=-20, ymax=20)
				</verbatim>